#!/usr/bin/env python3
import sys
from pathlib import Path


SAMPLES = [
    ("DROP", "msx/drop.raw"),
    ("ROTATE", "msx/rotate.raw"),
    ("SHAKE1", "msx/1shake.raw"),
    ("SHAKE2", "msx/2shake.raw"),
    ("SHAKE3", "msx/3shake.raw"),
    ("SHAKE4", "msx/4shake.raw"),
]


def emit_array(name: str, data: bytes) -> list[str]:
    lines = [
        f"    {name}_RAW_SIZE = {len(data)};",
        f"    {name}_RAW_DATA: array[0..{len(data) - 1}] of byte = (",
    ]
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        values = ",".join(f"${byte:02x}" for byte in chunk)
        suffix = "," if offset + 16 < len(data) else ""
        lines.append(f"        {values}{suffix}")
    lines.append("    );")
    lines.append("")
    return lines


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: raw2pas.py <project-root> <output-inc>", file=sys.stderr)
        return 2

    root = Path(sys.argv[1])
    output = Path(sys.argv[2])
    lines = [
        "{ generated by tools/raw2pas.py; do not edit by hand }",
        "",
    ]

    for name, rel_path in SAMPLES:
        lines.extend(emit_array(name, (root / rel_path).read_bytes()))

    output.write_text("\n".join(lines), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
